- name: Provision next thing co chip to send midi data from line6 fbv over wifi
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  raw: apt-get -y install python-simplejson
  roles:
    - { role: common, tags: ['common'] }
    - { role: puredata, tags: ['puredata'] }
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
    - name: reload systemd
      become: yes
      command: systemctl daemon-reload