- name: copy default puredata patch over
  template:
    src: templates/remoteMidi.pd
    dest: "/home/chip/remoteMidi.pd"
    owner: root
    mode: 0755

- name: install a service file for systemd to launch
  template:
    src: templates/pd_run.service
    dest: /etc/systemd/system/pd_run.service
    owner: root
    mode: 0755

- name: install a service file for systemd to launch
  template:
    src: templates/pd_run.sh
    dest: "/home/chip/pd_run.sh"
    owner: root
    mode: 0755
  notify: reload systemd

- name: enable the pd_run service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: pd_run
  notify: reload systemd

- name: install a udev rule to launch pd when foot controller is connected
  template:
    src: templates/pd.rules
    dest: /etc/udev/rules.d/pd.rules
    owner: root
    mode: 0644
